<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/11/19 20:51:11

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bbs',
  'username' => 'root',
  'password' => 'pa55w0rd',
  'name' => 'doctrine',
)),);
