<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/04 21:13:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bbs',
  'username' => 'root',
  'password' => 'password',
  'name' => 'doctrine',
)),);
