<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/04 20:30:25

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bbs',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
